In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
import sklearn.pipeline
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.ensemble import IsolationForest
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay

In [2]:
df = pd.read_csv('E:\Downloads\AIML Dataset.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

In [4]:
df.shape

(6362620, 11)

In [5]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [6]:
df.info()
df.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.0,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.00,0,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.00,0,0
6,1,PAYMENT,7107.77,C154988899,183195.00,176087.23,M408069119,0.0,0.00,0,0
7,1,PAYMENT,7861.64,C1912850431,176087.23,168225.59,M633326333,0.0,0.00,0,0
8,1,PAYMENT,4024.36,C1265012928,2671.00,0.00,M1176932104,0.0,0.00,0,0
9,1,DEBIT,5337.77,C712410124,41720.00,36382.23,C195600860,41898.0,40348.79,0,0
10,1,DEBIT,9644.94,C1900366749,4465.00,0.00,C997608398,10845.0,157982.12,0,0
11,1,PAYMENT,3099.97,C249177573,20771.00,17671.03,M2096539129,0.0,0.00,0,0
12,1,PAYMENT,2560.74,C1648232591,5070.00,2509.26,M972865270,0.0,0.00,0,0
13,1,PAYMENT,11633.76,C1716932897,10127.00,0.00,M801569151,0.0,0.00,0,0
14,1,PAYMENT,4098.78,C1026483832,503264.00,499165.22,M1635378213,0.0,0.00,0,0
15,1,CASH_OUT,229133.94,C905080434,15325.00,0.00,C476402209,5083.0,51513.44,0,0
16,1,PAYMENT,1563.82,C761750706,450.00,0.00,M1731217984,0.0,0.00,0,0
17,1,PAYMENT,1157.86,C1237762639,21156.00,19998.14,M1877062907,0.0,0.00,0,0
18,1,PAYMENT,671.64,C2033524545,15123.00,14451.36,M473053293,0.0,0.00,0,0
19,1,TRANSFER,215310.30,C1670993182,705.00,0.00,C1100439041,22425.0,0.00,0,0

type payment doesnt reflect in the destinations balance as it is a a system fee or a mobile payment 
type cashout and tranfer however SHOULD reflect

In [7]:
#encoding categorical variables

categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [8]:
df.head()
df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
6362615,743,1,339682.13,5651847,339682.13,0.0,505863,0.00,339682.13,1,0
6362616,743,4,6311409.28,1737278,6311409.28,0.0,260949,0.00,0.00,1,0
6362617,743,1,6311409.28,533958,6311409.28,0.0,108224,68488.84,6379898.11,1,0
6362618,743,4,850002.52,2252932,850002.52,0.0,319713,0.00,0.00,1,0
6362619,743,1,850002.52,919229,850002.52,0.0,534595,6510099.11,7360101.63,1,0

In [9]:
print (df.isnull().sum())

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [10]:
print (df.duplicated().sum())

0

In [11]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,0
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,0
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,0
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,0
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,0

not removing outliers since outlier ARE THE FRAUDS

In [12]:
#df.rename(columns={
 #   'oldbalanceOrg': 'oldbalanceSender',
  #  'newbalanceOrg': 'newbalanceSender',
   # 'oldbalanceDest': 'oldbalanceReceiver',
    #'newbalanceDest': 'newbalanceReceiver'
#}, inplace=True)

In [13]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,0
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,0
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,0
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,0
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,0

In [14]:
df.rename(columns={
    'oldbalanceOrg': 'oldbalanceSender',
    'newbalanceOrig': 'newbalanceSender',
    'oldbalanceDest': 'oldbalanceReceiver',
    'newbalanceDest': 'newbalanceReceiver'
}, inplace=True)

In [15]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,isFlaggedFraud
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,0
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,0
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,0
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,0
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,0

In [16]:
 #Flag if sender ends up with a negative balance
df['flag_sender_negative_balance'] = (df['newbalanceSender'] < 0).astype(int)

In [17]:

#Flag if receiver ends up with a negative balance
df['flag_receiver_negative_balance'] = (df['newbalanceReceiver'] < 0).astype(int)

In [18]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,isFlaggedFraud,flag_sender_negative_balance,flag_receiver_negative_balance
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,0,0,0
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,0,0,0
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,0,0,0
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,0,0,0
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,0,0,0

In [66]:
#senderside flag
df['flag_senderside'] = ((df['oldbalanceSender'].round(2) - df['newbalanceSender'].round(2) - df['amount']).abs() > 1e-6).astype(int)

In [67]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,...,flag_receiver_negative_balance,flag_senderside,flag_receiverside,flag_disappeared,flag_selftransfer,median_transactionamount_x,flag_above_median_spend,flag_amount_zero_but_balances_change,flag_fast_cashout,median_transactionamount_y
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,...,0,0,0,0,0,9839.64,0,0,0,9839.64
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,...,0,0,0,0,0,1864.28,0,0,0,1864.28
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,...,0,0,0,1,0,181.00,0,0,0,181.00
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,...,0,0,0,0,0,181.00,0,0,0,181.00
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,...,0,0,0,0,0,11668.14,0,0,0,11668.14

In [68]:
#recieverside flag
valid_receiver_txn = df['type'].isin(['TRANSFER', 'CASH_OUT'])

receiver_diff = (df['newbalanceReceiver'].round(2) - df['oldbalanceReceiver'].round(2) - df['amount'].round(2)).abs()

receiver_skipped = (df['oldbalanceReceiver'].round(2) == 0) & (df['newbalanceReceiver'].round(2) == 0)

df['flag_receiverside'] = ((receiver_diff > 1e-6) & ~receiver_skipped & valid_receiver_txn).astype(int)

In [69]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,...,flag_receiver_negative_balance,flag_senderside,flag_receiverside,flag_disappeared,flag_selftransfer,median_transactionamount_x,flag_above_median_spend,flag_amount_zero_but_balances_change,flag_fast_cashout,median_transactionamount_y
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,...,0,0,0,0,0,9839.64,0,0,0,9839.64
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,...,0,0,0,0,0,1864.28,0,0,0,1864.28
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,...,0,0,0,1,0,181.00,0,0,0,181.00
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,...,0,0,0,0,0,181.00,0,0,0,181.00
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,...,0,0,0,0,0,11668.14,0,0,0,11668.14

now moving on to phantom transactions the untracked ones

In [70]:
#Flag phantom transactions
df['flag_disappeared'] = (
    df['type'].isin([1, 4]) &  # TRANSFER or CASH_OUT (numeric)
    (df['flag_senderside'] == 0) &  # Sender deducted correctly
    ((df['oldbalanceReceiver'] - df['newbalanceReceiver']).abs() < 1e-6) &  # Receiver saw no change
    (df['amount'] > 0)  # Actual money moved
).astype(int)

In [71]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,...,flag_receiver_negative_balance,flag_senderside,flag_receiverside,flag_disappeared,flag_selftransfer,median_transactionamount_x,flag_above_median_spend,flag_amount_zero_but_balances_change,flag_fast_cashout,median_transactionamount_y
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,...,0,0,0,0,0,9839.64,0,0,0,9839.64
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,...,0,0,0,0,0,1864.28,0,0,0,1864.28
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,...,0,0,0,1,0,181.00,0,0,0,181.00
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,...,0,0,0,0,0,181.00,0,0,0,181.00
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,...,0,0,0,0,0,11668.14,0,0,0,11668.14

In [72]:
#df = df.drop(['isFlaggedFraud'],axis=1)

In [73]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,...,flag_receiver_negative_balance,flag_senderside,flag_receiverside,flag_disappeared,flag_selftransfer,median_transactionamount_x,flag_above_median_spend,flag_amount_zero_but_balances_change,flag_fast_cashout,median_transactionamount_y
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,...,0,0,0,0,0,9839.64,0,0,0,9839.64
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,...,0,0,0,0,0,1864.28,0,0,0,1864.28
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,...,0,0,0,1,0,181.00,0,0,0,181.00
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,...,0,0,0,0,0,181.00,0,0,0,181.00
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,...,0,0,0,0,0,11668.14,0,0,0,11668.14

In [74]:
df['flag_selftransfer'] = (
        (df['nameOrig'] == df['nameDest']) &  # Same account
        (df['type'] != 1) &  # Not a TRANSFER
        (df['amount'] > 0)  # Actual money moved
).astype(int)

In [75]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,...,flag_receiver_negative_balance,flag_senderside,flag_receiverside,flag_disappeared,flag_selftransfer,median_transactionamount_x,flag_above_median_spend,flag_amount_zero_but_balances_change,flag_fast_cashout,median_transactionamount_y
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,...,0,0,0,0,0,9839.64,0,0,0,9839.64
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,...,0,0,0,0,0,1864.28,0,0,0,1864.28
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,...,0,0,0,1,0,181.00,0,0,0,181.00
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,...,0,0,0,0,0,181.00,0,0,0,181.00
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,...,0,0,0,0,0,11668.14,0,0,0,11668.14

In [76]:
#checking if any flags are raised
flag_columns = [col for col in df.columns if col.startswith('flag_')]
df[flag_columns].sum()

flag_sender_negative_balance                  0
flag_receiver_negative_balance                0
flag_senderside                         5125552
flag_receiverside                             0
flag_disappeared                           4486
flag_selftransfer                             2
flag_above_median_spend                       3
flag_amount_zero_but_balances_change          0
flag_fast_cashout                             0
dtype: int64

In [77]:
#viewing rows with any flag raised
df[df[flag_columns].sum(axis=1) > 0]

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,...,flag_receiver_negative_balance,flag_senderside,flag_receiverside,flag_disappeared,flag_selftransfer,median_transactionamount_x,flag_above_median_spend,flag_amount_zero_but_balances_change,flag_fast_cashout,median_transactionamount_y
2,1,4,181.00,1002156,181.00,0.0,439685,0.0,0.00,1,...,0,0,0,1,0,181.00,0,0,0,181.00
8,1,3,4024.36,869140,2671.00,0.0,768940,0.0,0.00,0,...,0,1,0,0,0,4024.36,0,0,0,4024.36
10,1,2,9644.94,2957937,4465.00,0.0,571261,10845.0,157982.12,0,...,0,1,0,0,0,9644.94,0,0,0,9644.94
13,1,3,11633.76,2355062,10127.00,0.0,2501242,0.0,0.00,0,...,0,1,0,0,0,11633.76,0,0,0,11633.76
15,1,1,229133.94,6041662,15325.00,0.0,417183,5083.0,51513.44,0,...,0,1,0,0,0,229133.94,0,0,0,229133.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6362610,742,4,63416.99,5623928,63416.99,0.0,240455,0.0,0.00,1,...,0,0,0,1,0,63416.99,0,0,0,63416.99
6362612,743,4,1258818.82,1744853,1258818.82,0.0,139604,0.0,0.00,1,...,0,0,0,1,0,1258818.82,0,0,0,1258818.82
6362614,743,4,339682.13,3332123,339682.13,0.0,251708,0.0,0.00,1,...,0,0,0,1,0,339682.13,0,0,0,339682.13
6362616,743,4,6311409.28,1737278,6311409.28,0.0,260949,0.0,0.00,1,...,0,0,0,1,0,6311409.28,0,0,0,6311409.28
6362618,743,4,850002.52,2252932,850002.52,0.0,319713,0.0,0.00,1,...,0,0,0,1,0,850002.52,0,0,0,850002.52

In [78]:
#Group by sender and compute median transaction amount
sender_median = df.groupby('nameOrig')['amount'].median().rename('median_transactionamount')
#Merge back into the main DataFrame
df = df.merge(sender_median, left_on='nameOrig', right_index=True)

In [79]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,...,flag_senderside,flag_receiverside,flag_disappeared,flag_selftransfer,median_transactionamount_x,flag_above_median_spend,flag_amount_zero_but_balances_change,flag_fast_cashout,median_transactionamount_y,median_transactionamount
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,...,0,0,0,0,9839.64,0,0,0,9839.64,9839.64
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,...,0,0,0,0,1864.28,0,0,0,1864.28,1864.28
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,...,0,0,1,0,181.00,0,0,0,181.00,181.00
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,...,0,0,0,0,181.00,0,0,0,181.00,181.00
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,...,0,0,0,0,11668.14,0,0,0,11668.14,11668.14

In [80]:
#Flag transactions that are 3 times or more above personal median
df['flag_above_median_spend'] = (
    df['type'].isin([1, 4]) &  #Only apply to TRANSFER and CASH_OUT
    (df['amount'] > 3 * df['median_transactionamount'])
).astype(int)

In [81]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,...,flag_senderside,flag_receiverside,flag_disappeared,flag_selftransfer,median_transactionamount_x,flag_above_median_spend,flag_amount_zero_but_balances_change,flag_fast_cashout,median_transactionamount_y,median_transactionamount
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,...,0,0,0,0,9839.64,0,0,0,9839.64,9839.64
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,...,0,0,0,0,1864.28,0,0,0,1864.28,1864.28
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,...,0,0,1,0,181.00,0,0,0,181.00,181.00
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,...,0,0,0,0,181.00,0,0,0,181.00,181.00
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,...,0,0,0,0,11668.14,0,0,0,11668.14,11668.14

In [82]:
#flag transactions where amount is zero but balances change
#This checks if the transaction type is TRANSFER or CASH_OUT, amount is zero, and
#balances change for either sender or receiver, excluding cases where all balances are zero

df['flag_amount_zero_but_balances_change'] = (
    (df['type'].isin([1, 4])) &
    (df['amount'].round(2) == 0) &
    (
        (df['oldbalanceSender'].round(2) != df['newbalanceSender'].round(2)) |
        (df['oldbalanceReceiver'].round(2) != df['newbalanceReceiver'].round(2))
    ) &
    ~(
        (df['oldbalanceSender'].round(2) == 0) &
        (df['oldbalanceReceiver'].round(2) == 0) &
        (df['newbalanceSender'].round(2) == 0) &
        (df['newbalanceReceiver'].round(2) == 0)
    )
).astype(int)

In [83]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,...,flag_senderside,flag_receiverside,flag_disappeared,flag_selftransfer,median_transactionamount_x,flag_above_median_spend,flag_amount_zero_but_balances_change,flag_fast_cashout,median_transactionamount_y,median_transactionamount
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,...,0,0,0,0,9839.64,0,0,0,9839.64,9839.64
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,...,0,0,0,0,1864.28,0,0,0,1864.28,1864.28
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,...,0,0,1,0,181.00,0,0,0,181.00,181.00
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,...,0,0,0,0,181.00,0,0,0,181.00,181.00
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,...,0,0,0,0,11668.14,0,0,0,11668.14,11668.14

In [84]:
#checking if any flags are raised
flag_columns = [col for col in df.columns if col.startswith('flag_')]
df[flag_columns].sum()

flag_sender_negative_balance                  0
flag_receiver_negative_balance                0
flag_senderside                         5125552
flag_receiverside                             0
flag_disappeared                           4486
flag_selftransfer                             2
flag_above_median_spend                       3
flag_amount_zero_but_balances_change          0
flag_fast_cashout                             0
dtype: int64

In [85]:
#Sort data for sequence-based logic
df_sorted = df.sort_values(by=['nameDest', 'step']).reset_index(drop=True)

#Shift relevant columns to get the *next transaction* by the same account
df_sorted['next_step'] = df_sorted['step'].shift(-1)
df_sorted['next_type'] = df_sorted['type'].shift(-1)
df_sorted['next_amount'] = df_sorted['amount'].shift(-1)
df_sorted['next_nameOrig'] = df_sorted['nameOrig'].shift(-1)

#Build the fast cashout flag
df_sorted['flag_fast_cashout'] = (
    (df_sorted['type'] == 1) &  # TRANSFER
    (df_sorted['next_type'] == 4) &  # followed by CASH_OUT
    (df_sorted['nameDest'] == df_sorted['next_nameOrig']) &  # same person
    (df_sorted['amount'].round(2) == df_sorted['next_amount'].round(2)) &  # same amount
    ((df_sorted['next_step'] - df_sorted['step']) <= 2)  # fast: within 2 time steps
).astype(int)

df['flag_fast_cashout'] = df_sorted['flag_fast_cashout']

In [86]:
df.head()

,step,type,amount,nameOrig,oldbalanceSender,newbalanceSender,nameDest,oldbalanceReceiver,newbalanceReceiver,isFraud,...,flag_senderside,flag_receiverside,flag_disappeared,flag_selftransfer,median_transactionamount_x,flag_above_median_spend,flag_amount_zero_but_balances_change,flag_fast_cashout,median_transactionamount_y,median_transactionamount
0,1,3,9839.64,757869,170136.0,160296.36,1662094,0.0,0.0,0,...,0,0,0,0,9839.64,0,0,0,9839.64,9839.64
1,1,3,1864.28,2188998,21249.0,19384.72,1733924,0.0,0.0,0,...,0,0,0,0,1864.28,0,0,0,1864.28,1864.28
2,1,4,181.00,1002156,181.0,0.00,439685,0.0,0.0,1,...,0,0,1,0,181.00,0,0,0,181.00,181.00
3,1,1,181.00,5828262,181.0,0.00,391696,21182.0,0.0,1,...,0,0,0,0,181.00,0,0,0,181.00,181.00
4,1,3,11668.14,3445981,41554.0,29885.86,828919,0.0,0.0,0,...,0,0,0,0,11668.14,0,0,0,11668.14,11668.14

In [87]:
#checking if any flags are raised
flag_columns = [col for col in df.columns if col.startswith('flag_')]
df[flag_columns].sum()

flag_sender_negative_balance                  0
flag_receiver_negative_balance                0
flag_senderside                         5125552
flag_receiverside                             0
flag_disappeared                           4486
flag_selftransfer                             2
flag_above_median_spend                       3
flag_amount_zero_but_balances_change          0
flag_fast_cashout                             0
dtype: int64

In [ ]:
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score, make_scorer
import pandas as pd
import numpy as np

# Prepare data
df_sample = df.sample(n=200000, random_state=42)
columns_to_drop = [col for col in ['isFraud', 'nameOrig', 'nameDest'] if col in df.columns]
X = df_sample.drop(columns=columns_to_drop)
y_true = df['isFraud']

# Custom scoring function using F1 Score
def f1_scorer(estimator, X):
    y_pred = estimator.predict(X)
    y_pred = pd.Series(y_pred).map({1: 0, -1: 1})
    return f1_score(y_true, y_pred)

# Define pipeline
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('isoforest', IsolationForest(random_state=42))
])

# Define parameter distribution
param_dist = {
    'isoforest__n_estimators': [100, 200, 300],
    'isoforest__max_samples': ['auto', 0.5, 0.7, 0.9],
    'isoforest__contamination': np.linspace(0.001, 0.01, 10),
    'isoforest__max_features': [0.6, 0.8, 1.0]
}

# Setup RandomizedSearchCV
random_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_dist,
    n_iter=20,
    scoring=f1_scorer,
    cv=2,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# Run the search
random_search.fit(X)

# Best model and parameters
best_model = random_search.best_estimator_
print("Best Parameters:", random_search.best_params_)

Fitting 2 folds for each of 20 candidates, totalling 40 fits

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score, precision_score, recall_score, f1_score
import numpy as np
import pandas as pd

# Rebuild pipeline with best parameters
final_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('isoforest', IsolationForest(
        n_estimators=300,
        max_samples=0.7,
        max_features=0.6,
        contamination=0.007,
        random_state=42
    ))
])

# Fit the pipeline
final_pipeline.fit(X)

# Predict and map output
y_true = df_sample['isFraud'].reset_index(drop=True)
y_pred = final_pipeline.predict(X)
y_pred = pd.Series(y_pred).map({1: 0, -1: 1})  # 0: normal, 1: anomaly/fraud

# Evaluation
print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
print("\nClassification Report:\n", classification_report(y_true, y_pred))
print("ROC-AUC Score:", roc_auc_score(y_true, y_pred))
print("Precision:", precision_score(y_true, y_pred))
print("Recall:", recall_score(y_true, y_pred))
print("F1 Score:", f1_score(y_true, y_pred))

# Optional: Add predictions to your sampled dataframe
df_sample['anomaly_score'] = y_pred


accuracy = accuracy_score(y_true, y_pred)
print("Accuracy:", accuracy)

Confusion Matrix:
 [[198515   1217]
 [    85    183]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      1.00    199732
           1       0.13      0.68      0.22       268

    accuracy                           0.99    200000
   macro avg       0.57      0.84      0.61    200000
weighted avg       1.00      0.99      1.00    200000

ROC-AUC Score: 0.838371328027318
Precision: 0.13071428571428573
Recall: 0.6828358208955224
F1 Score: 0.21942446043165467
Accuracy: 0.99349